# In this job we will add multple job in the job
name: "Second Job"
on:
  workflow_dispatch:
jobs:
  say-hello-from-bash:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello world"
  say-hello-from-python:
    needs: say-hello-from-bash
    runs-on: ubuntu-24.04
    steps:
      - run : print("Hello from python")
        shell: python
